[build]
  command = "npx prisma migrate deploy && npm run prisma:generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.15.0"
  NEXT_FORCE_EDGE_IMAGES = "false"

  NEXTAUTH_SECRET = "MMM"
  NEXTAUTH_URL = "https://linkalbum.netlify.app/api/v1/auth"
  PORT = "3000"
  DATABASE_URL = "postgresql://neondb_owner:npg_G9fZmzCIN2vp@ep-twilight-sound-aeobgvlq-pooler.c-2.us-east-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
  NETLIFY_DATABASE_URL = "postgresql://neondb_owner:npg_G9fZmzCIN2vp@ep-twilight-sound-aeobgvlq-pooler.c-2.us-east-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require"

  # Netlify Blobs is enabled by default in Functions - no manual configuration needed
  USE_NETLIFY_BLOBS = "true"

  STORAGE_FOLDER = "archives"
  AUTOSCROLL_TIMEOUT = "1000"
  NEXT_PUBLIC_DISABLE_REGISTRATION = "false"
  NEXT_PUBLIC_CREDENTIALS_ENABLED = "true"
  DISABLE_NEW_SSO_USERS = "false"
  RE_ARCHIVE_LIMIT = "30"
  NEXT_PUBLIC_MAX_FILE_SIZE = "5000000"
  MAX_LINKS_PER_USER = "1000"
  ARCHIVE_TAKE_COUNT = "10"
  BROWSER_TIMEOUT = "30000"
  IGNORE_UNAUTHORIZED_CA = "false"
  ENABLE_MONOLITH = "false"
  SPACES_ENDPOINT = "http://toolhub-1767803014225877.oss-cn-beijing.oss-accesspoint.aliyuncs.com"
  SPACES_BUCKET_NAME = "linkwarden"
  SPACES_REGION = "cn-beijing"
  SPACES_FORCE_PATH_STYLE = "true"

  # Function processing settings
  ARCHIVE_SCRIPT_INTERVAL = "60"  # 60 seconds between batch runs
  DISABLE_PRESERVATION = "false"
  
  # Browser settings for Playwright
  SCREENSHOTONE_API_KEY = "th7Lw0HWLdwzPw"

# Functions configuration - use the main /functions directory
[functions]
  directory = "/netlify/functions"

# Development configuration
[dev]
  framework = "next"
  command = "npm run dev"
  targetPort = 3000

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/links/process"
  to = "/.netlify/functions/process-link"
  status = 200

[[redirects]]
  from = "/api/process-batch"
  to = "/.netlify/functions/process-links-batch"
  status = 200

[[redirects]]
  from = "/api/process-rss"
  to = "/.netlify/functions/process-rss"
  status = 200

# Blob operation redirects
[[redirects]]
  from = "/api/blobs/create"
  to = "/.netlify/functions/blob-create"
  status = 200

[[redirects]]
  from = "/api/blobs/read"
  to = "/.netlify/functions/blob-read"
  status = 200

[[redirects]]
  from = "/api/blobs/delete"
  to = "/.netlify/functions/blob-delete"
  status = 200

[[redirects]]
  from = "/api/blobs/move"
  to = "/.netlify/functions/blob-move"
  status = 200