[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_FORCE_EDGE_IMAGES = "false"

[functions]
  node_bundler = "nft"
  # Disable edge functions to avoid Deno bundling issues
  edge_bundler = "none"

# Disable Next.js Runtime Edge Functions features that cause bundling issues  
[functions."___netlify-odb-handler"]
  included_files = []