[build]
  command = "yarn prisma generate && yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.15.0"
  NEXT_FORCE_EDGE_IMAGES = "false"

  NEXTAUTH_SECRET = "MMM"
  NEXTAUTH_URL = "https://linkalbum.netlify.app/api/v1/auth"
  DATABASE_URL = "postgresql://may:410410@127.0.0.1:5432/linkwarden"
  POSTGRES_PASSWORD = "410410"
  PORT = "3000"
  STORAGE_FOLDER = "archives"
  AUTOSCROLL_TIMEOUT = "1000"
  NEXT_PUBLIC_DISABLE_REGISTRATION = "false"
  NEXT_PUBLIC_CREDENTIALS_ENABLED = "true"
  DISABLE_NEW_SSO_USERS = "false"
  RE_ARCHIVE_LIMIT = "30"
  NEXT_PUBLIC_MAX_FILE_SIZE = "5000000"
  MAX_LINKS_PER_USER = "1000"
  ARCHIVE_TAKE_COUNT = "10"
  BROWSER_TIMEOUT = "30000"
  IGNORE_UNAUTHORIZED_CA = "false"
  ENABLE_MONOLITH = "false"
  SPACES_KEY = "***REMOVED***"
  SPACES_SECRET = "***REMOVED***"
  SPACES_ENDPOINT = "http://toolhub-1767803014225877.oss-cn-beijing.oss-accesspoint.aliyuncs.com"
  SPACES_BUCKET_NAME = "linkwarden"
  SPACES_REGION = "cn-beijing"
  SPACES_FORCE_PATH_STYLE = "true"